### ISSUE TITLE
move to ensime org?

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-cloud9#54]
Would you not prefer to be seen on ensime.org and github.com/ensime ?

**Comment by msiegenthaler** [comment]
sure, great idea.
let's do that

**Comment by fommil** [comment]
:-) transfer to me then I'll transfer to ensime and add you as the owner, then you fork back to here.  You can use our drone CI.

**Comment by fommil** [comment]
Looks like it landed :-). I'll add you with all the permissions tomorrow, it's late here. For now, fork back into your personal repo to preserve the Google links, and send a PR to the docs page advertising this project, and welcome to the group!
